-- [최종 보안 및 호환성 패치] Spring Session JDBC PostgreSQL 인코딩 에러(0x00) 완벽 해결 스키마
-- 쿠키 이름 변경(V2)과 병행하여 기존 데이터를 완전히 제거하고 유연한 TEXT 타입을 사용합니다.

DROP TABLE IF EXISTS SPRING_SESSION_ATTRIBUTES CASCADE;
DROP TABLE IF EXISTS SPRING_SESSION CASCADE;

CREATE TABLE SPRING_SESSION (
    PRIMARY_ID TEXT NOT NULL,
    SESSION_ID TEXT NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME TEXT,
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID TEXT NOT NULL,
    ATTRIBUTE_NAME TEXT NOT NULL,
    ATTRIBUTE_BYTES BYTEA NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
