-- [추가 최적화] Spring Session 테이블의 필드 타입을 TEXT로 전환하여 호환성을 극대화합니다.
-- V15에서 생성된 테이블의 타입을 정밀하게 조정합니다.

ALTER TABLE SPRING_SESSION ALTER COLUMN PRIMARY_ID TYPE TEXT;
ALTER TABLE SPRING_SESSION ALTER COLUMN SESSION_ID TYPE TEXT;
ALTER TABLE SPRING_SESSION ALTER COLUMN PRINCIPAL_NAME TYPE TEXT;

ALTER TABLE SPRING_SESSION_ATTRIBUTES ALTER COLUMN SESSION_PRIMARY_ID TYPE TEXT;
ALTER TABLE SPRING_SESSION_ATTRIBUTES ALTER COLUMN ATTRIBUTE_NAME TYPE TEXT;
