-- V17: 제조사 Audit 관리 시스템 구축

-- 1. Audit 분류 테이블 (화장품 제조사, 사료 제조사 등)
CREATE TABLE audit_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_name VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. 점검항목 그룹 테이블 (운영관리, 위생관리 등)
CREATE TABLE audit_template_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    group_name VARCHAR(100) NOT NULL,
    display_order INT DEFAULT 0,
    FOREIGN KEY (template_id) REFERENCES audit_templates(id) ON DELETE CASCADE
);

-- 3. 세부항목 테이블 (실제 평가 문항)
CREATE TABLE audit_template_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    item_content TEXT NOT NULL,
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (group_id) REFERENCES audit_template_groups(id) ON DELETE CASCADE
);

-- 4. 제조사 Audit 결과 메인 테이블
CREATE TABLE manufacturer_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_date DATE NOT NULL,
    manufacturer_id BIGINT NOT NULL,
    template_id BIGINT NOT NULL,
    audit_type VARCHAR(50) NOT NULL, -- 신규, 정기, 비정기
    total_score INT DEFAULT 0,
    grade VARCHAR(5) DEFAULT 'F',
    final_evaluation TEXT,
    report_file_url VARCHAR(255),
    modifier_info VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (manufacturer_id) REFERENCES manufacturers(id),
    FOREIGN KEY (template_id) REFERENCES audit_templates(id)
);

-- 5. Audit 세부 점수 테이블
CREATE TABLE manufacturer_audit_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    score INT CHECK (score >= 1 AND score <= 5),
    remarks TEXT,
    FOREIGN KEY (audit_id) REFERENCES manufacturer_audits(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES audit_template_items(id)
);

-- 6. 초기 데이터 시딩 (분류 및 점검항목)
-- 6-1. 분류 등록
INSERT INTO audit_templates (classification_name) VALUES ('화장품 제조사 Audit');
INSERT INTO audit_templates (classification_name) VALUES ('공산품 제조사 Audit');
INSERT INTO audit_templates (classification_name) VALUES ('화장품 용기 제조사 Audit');
INSERT INTO audit_templates (classification_name) VALUES ('사료 제조사 Audit');
INSERT INTO audit_templates (classification_name) VALUES ('동물용 의약외품 제조사 Audit');

-- 6-2. 화장품 제조사용 점검항목 그룹 등록
DO $$
DECLARE
    t_id BIGINT;
BEGIN
    SELECT id INTO t_id FROM audit_templates WHERE classification_name = '화장품 제조사 Audit';
    
    INSERT INTO audit_template_groups (template_id, group_name, display_order) VALUES (t_id, '운영관리', 1);
    INSERT INTO audit_template_groups (template_id, group_name, display_order) VALUES (t_id, '위생관리', 2);
    INSERT INTO audit_template_groups (template_id, group_name, display_order) VALUES (t_id, '공정관리', 3);
    INSERT INTO audit_template_groups (template_id, group_name, display_order) VALUES (t_id, '품질관리', 4);
    INSERT INTO audit_template_groups (template_id, group_name, display_order) VALUES (t_id, '교육관리', 5);
    INSERT INTO audit_template_groups (template_id, group_name, display_order) VALUES (t_id, '클레임관리', 6);
END $$;

-- 6-3. 화장품 제조사 > 위생관리 세부항목 시딩 (예시 5개)
DO $$
DECLARE
    g_id BIGINT;
BEGIN
    SELECT g.id INTO g_id 
    FROM audit_template_groups g 
    JOIN audit_templates t ON g.template_id = t.id 
    WHERE t.classification_name = '화장품 제조사 Audit' AND g.group_name = '위생관리';
    
    INSERT INTO audit_template_items (group_id, item_content, display_order) VALUES (g_id, '작업장 바닥, 벽, 천장의 청결 상태', 1);
    INSERT INTO audit_template_items (group_id, item_content, display_order) VALUES (g_id, '작업자의 위생복, 위생모, 위생화 착용 준수', 2);
    INSERT INTO audit_template_items (group_id, item_content, display_order) VALUES (g_id, '제조 설비 및 도구의 세척/소독 관리 상태', 3);
    INSERT INTO audit_template_items (group_id, item_content, display_order) VALUES (g_id, '폐기물 처리 및 보관 구역의 격리 상태', 4);
    INSERT INTO audit_template_items (group_id, item_content, display_order) VALUES (g_id, '외부 오염물질 유입 방지(방충/방서) 시설 관리', 5);
END $$;

-- 다른 분류 및 그룹에 대해서도 동일한 방식으로 시딩 (실제 구현 시 더 많은 항목 추가)
