-- V28: Manufacturer Audit Auditor Field and History Table
ALTER TABLE manufacturer_audits ADD COLUMN auditor VARCHAR(255);

CREATE TABLE manufacturer_audit_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id BIGINT NOT NULL,
    modifier VARCHAR(255) NOT NULL,
    modifier_id BIGINT,
    modifier_username VARCHAR(255),
    modifier_name VARCHAR(255),
    modifier_company VARCHAR(255),
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    field_name VARCHAR(255),
    old_value TEXT,
    new_value TEXT
);

CREATE INDEX idx_audit_history_audit_id ON manufacturer_audit_history(audit_id);
