-- V39_2: V40 products 인덱스 추가 전 products 테이블 필요 컬럼 안전 보강
ALTER TABLE products ADD COLUMN IF NOT EXISTS item_code VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_name VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand_id BIGINT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS manufacturer_id BIGINT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
