package com.example.ims.service;

import com.example.ims.dto.dynamic.DashboardDto;
import com.example.ims.entity.*;
import com.example.ims.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class DynamicDashboardService {

    private final DynamicDashboardRepository dashboardRepository;
    private final DashboardWidgetRepository widgetRepository;
    private final DynamicScreenRepository screenRepository;
    private final ScreenGridColumnRepository gridColumnRepository;
    private final WidgetCatalogRepository widgetCatalogRepository;

    @Transactional(readOnly = true)
    public Optional<DashboardDto> getDashboardByScreenId(Long screenId) {
        return dashboardRepository.findFirstBySourceScreenIdOrderByCreatedAtDesc(screenId)
                .map(this::toDto);
    }

    @Transactional
    public DashboardDto autoGenerateDashboard(Long screenId, Long userId) {
        DynamicScreen screen = screenRepository.findById(screenId)
                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 동적 화면 ID: " + screenId));

        List<ScreenGridColumn> columns = gridColumnRepository.findByScreenIdOrderByDisplayOrderAsc(screenId);

        // 1. 기존 대시보드가 있으면 위젯들 정리 후 갱신, 없으면 신규 생성
        DynamicDashboard dashboard = dashboardRepository.findFirstBySourceScreenIdOrderByCreatedAtDesc(screenId)
                .orElseGet(() -> DynamicDashboard.builder()
                        .sourceScreen(screen)
                        .dashboardName(screen.getScreenName() + " 자동 분석 대시보드")
                        .createdBy(userId)
                        .build());
        dashboard = dashboardRepository.save(dashboard);

        // 기존 위젯 삭제
        widgetRepository.deleteByDashboardId(dashboard.getId());

        // 2. 규칙 기반 위젯 자동 생성 엔진
        List<ScreenGridColumn> measures = columns.stream()
                .filter(c -> Boolean.TRUE.equals(c.getIsMeasure()) && !Boolean.TRUE.equals(c.getIsExcludedFromDashboard()))
                .collect(Collectors.toList());

        List<ScreenGridColumn> dimensions = columns.stream()
                .filter(c -> Boolean.TRUE.equals(c.getIsDimension()) && !Boolean.TRUE.equals(c.getIsExcludedFromDashboard()))
                .collect(Collectors.toList());

        Optional<ScreenGridColumn> primaryDateOpt = columns.stream()
                .filter(c -> Boolean.TRUE.equals(c.getIsPrimaryDate()))
                .findFirst();

        List<DashboardWidget> widgets = new ArrayList<>();
        int currentX = 0;
        int currentY = 0;

        WidgetCatalog kpiCatalog = widgetCatalogRepository.findByWidgetType("KPI_CARD").orElse(null);
        WidgetCatalog lineCatalog = widgetCatalogRepository.findByWidgetType("LINE_CHART").orElse(null);
        WidgetCatalog barCatalog = widgetCatalogRepository.findByWidgetType("BAR_CHART").orElse(null);
        WidgetCatalog pieCatalog = widgetCatalogRepository.findByWidgetType("PIE_CHART").orElse(null);

        // Rule 1: 모든 수치(Measure) 필드 -> 상단 KPI 카드 위젯 배치 (폭 3, 높이 2)
        if (kpiCatalog != null) {
            for (ScreenGridColumn m : measures) {
                DashboardWidget widget = DashboardWidget.builder()
                        .dashboard(dashboard)
                        .widget(kpiCatalog)
                        .boundFieldKey(m.getFieldKey())
                        .title("총 " + m.getLabel())
                        .positionX(currentX)
                        .positionY(currentY)
                        .width(3)
                        .height(2)
                        .build();
                widgets.add(widget);
                currentX += 3;
                if (currentX >= 12) {
                    currentX = 0;
                    currentY += 2;
                }
            }
        }

        // 줄바꿈 (차트 영역으로 이동)
        if (currentX > 0) {
            currentX = 0;
            currentY += 2;
        }

        // Rule 2: 수치 + 기준 일자 -> 시계열 트렌드 라인 차트 배치 (폭 6, 높이 4)
        if (lineCatalog != null && primaryDateOpt.isPresent() && !measures.isEmpty()) {
            ScreenGridColumn primaryMeasure = measures.get(0);
            DashboardWidget lineWidget = DashboardWidget.builder()
                    .dashboard(dashboard)
                    .widget(lineCatalog)
                    .boundFieldKey(primaryMeasure.getFieldKey())
                    .secondaryFieldKey(primaryDateOpt.get().getFieldKey())
                    .title("일자별 " + primaryMeasure.getLabel() + " 추이")
                    .positionX(currentX)
                    .positionY(currentY)
                    .width(6)
                    .height(4)
                    .build();
            widgets.add(lineWidget);
            currentX += 6;
        }

        // Rule 3: 수치 + 분류 차원(Dimension) -> 카테고리별 막대 차트 배치 (폭 6, 높이 4)
        if (barCatalog != null && !dimensions.isEmpty() && !measures.isEmpty()) {
            ScreenGridColumn primaryDimension = dimensions.get(0);
            ScreenGridColumn primaryMeasure = measures.get(0);
            DashboardWidget barWidget = DashboardWidget.builder()
                    .dashboard(dashboard)
                    .widget(barCatalog)
                    .boundFieldKey(primaryMeasure.getFieldKey())
                    .secondaryFieldKey(primaryDimension.getFieldKey())
                    .title(primaryDimension.getLabel() + "별 " + primaryMeasure.getLabel() + " 분포")
                    .positionX(currentX)
                    .positionY(currentY)
                    .width(6)
                    .height(4)
                    .build();
            widgets.add(barWidget);
            currentX += 6;
            if (currentX >= 12) {
                currentX = 0;
                currentY += 4;
            }
        }

        // Rule 4: 두 번째 분류 차원이 있는 경우 -> 파이 차트 배치 (폭 6, 높이 4)
        if (pieCatalog != null && dimensions.size() >= 2) {
            ScreenGridColumn secondDimension = dimensions.get(1);
            DashboardWidget pieWidget = DashboardWidget.builder()
                    .dashboard(dashboard)
                    .widget(pieCatalog)
                    .boundFieldKey(secondDimension.getFieldKey())
                    .title(secondDimension.getLabel() + " 점유율 현황")
                    .positionX(currentX)
                    .positionY(currentY)
                    .width(6)
                    .height(4)
                    .build();
            widgets.add(pieWidget);
        }

        widgetRepository.saveAll(widgets);
        log.info("[DYNAMIC DASHBOARD] Auto-generated {} widgets for screenId={}, dashboardId={}", widgets.size(), screenId, dashboard.getId());

        return toDto(dashboard);
    }

    private DashboardDto toDto(DynamicDashboard dashboard) {
        List<DashboardWidget> widgets = widgetRepository.findByDashboardId(dashboard.getId());
        List<DashboardDto.WidgetDto> widgetDtos = widgets.stream().map(w -> 
            DashboardDto.WidgetDto.builder()
                    .id(w.getId())
                    .widgetType(w.getWidget().getWidgetType())
                    .componentKey(w.getWidget().getComponentKey())
                    .designToken(w.getWidget().getDesignToken())
                    .boundFieldKey(w.getBoundFieldKey())
                    .secondaryFieldKey(w.getSecondaryFieldKey())
                    .title(w.getTitle())
                    .positionX(w.getPositionX())
                    .positionY(w.getPositionY())
                    .width(w.getWidth())
                    .height(w.getHeight())
                    .build()
        ).collect(Collectors.toList());

        return DashboardDto.builder()
                .id(dashboard.getId())
                .sourceScreenId(dashboard.getSourceScreen() != null ? dashboard.getSourceScreen().getId() : null)
                .dashboardName(dashboard.getDashboardName())
                .createdBy(dashboard.getCreatedBy())
                .createdAt(dashboard.getCreatedAt())
                .widgets(widgetDtos)
                .build();
    }
}
