package com.example.ims.controller;

import com.example.ims.dto.dynamic.DashboardDto;
import com.example.ims.entity.User;
import com.example.ims.repository.UserRepository;
import com.example.ims.service.DynamicDashboardService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/dynamic/dashboards")
@RequiredArgsConstructor
@Slf4j
public class DynamicDashboardController {

    private final DynamicDashboardService dashboardService;
    private final UserRepository userRepository;

    private Long getCurrentUserId() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null && auth.isAuthenticated() && !"anonymousUser".equals(auth.getName())) {
            return userRepository.findByUsername(auth.getName())
                    .map(User::getId)
                    .orElse(null);
        }
        return null;
    }

    @GetMapping("/screen/{screenId}")
    public ResponseEntity<DashboardDto> getDashboardByScreenId(@PathVariable Long screenId) {
        return dashboardService.getDashboardByScreenId(screenId)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.noContent().build());
    }

    @PostMapping("/screen/{screenId}/auto-generate")
    public ResponseEntity<DashboardDto> autoGenerateDashboard(@PathVariable Long screenId) {
        Long userId = getCurrentUserId();
        DashboardDto dashboard = dashboardService.autoGenerateDashboard(screenId, userId);
        return ResponseEntity.ok(dashboard);
    }
}
